language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-static2000' ]; then cd .. && eval "mv $currentfolder generator-static2000" && cd generator-static2000; fi
